[package]
org = "wso2"
name = "online_shop"
version = "0.0.1"

[build-options]
cloud = "k8s"

[[platform.java11.dependency]]
groupId = "com.oracle.database.jdbc"
artifactId = "ojdbc8"
version = "12.2.0.1"

[[platform.java11.dependency]]
groupId = "com.oracle.database.xml"
artifactId = "xdb"
version = "21.1.0.0"

[[platform.java11.dependency]]
groupId = "com.oracle.database.xml"
artifactId = "xmlparserv2"
version = "12.2.0.1"
