[package]
org = "ballerinax"
name = "oracledb"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["database", "client", "network", "SQL", "RDBMS", "OracleDB", "Oracle"]
repository = "https://github.com/ballerina-platform/module-ballerinax-oracledb"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.7.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "oracledb-native"
version = "@toml.version@"
path = "../native/build/libs/oracledb-native-@project.version@.jar"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "sql-native"
version = "@sql.version@"
path = "./lib/sql-native-@stdlib.sql.native.version@.jar"

[[platform.java17.dependency]]
groupId = "com.oracle.database.jdbc"
artifactId = "ojdbc11"
version = "@ojdbc.version@"

[[platform.java17.dependency]]
groupId = "com.oracle.database.xml"
artifactId = "xdb"
version = "@xdb.version@"

[[platform.java17.dependency]]
groupId = "com.oracle.database.xml"
artifactId = "xmlparserv2"
version = "@xmlparser.version@"
