[package]
org = "ballerinax"
name = "oracledb"
version = "1.8.1"
authors = ["Ballerina"]
keywords = ["database", "client", "network", "SQL", "RDBMS", "OracleDB", "Oracle"]
repository = "https://github.com/ballerina-platform/module-ballerinax-oracledb"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.5.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "oracledb-native"
version = "1.8.1"
path = "../native/build/libs/oracledb-native-1.8.1-SNAPSHOT.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "sql-native"
version = "1.9.0"
path = "./lib/sql-native-1.9.0-20230524-142200-889b602.jar"
