[package]
org = "ballerinax"
name = "oracledb"
version = "1.10.1"
authors = ["Ballerina"]
keywords = ["database", "client", "network", "SQL", "RDBMS", "OracleDB", "Oracle"]
repository = "https://github.com/ballerina-platform/module-ballerinax-oracledb"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.7.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "oracledb-native"
version = "1.10.1"
path = "../native/build/libs/oracledb-native-1.10.1-SNAPSHOT.jar"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "sql-native"
version = "1.10.0"
path = "./lib/sql-native-1.10.0.jar"

[[platform.java17.dependency]]
groupId = "com.oracle.database.jdbc"
artifactId = "ojdbc11"
version = "23.2.0.0"

[[platform.java17.dependency]]
groupId = "com.oracle.database.xml"
artifactId = "xdb"
version = "23.2.0.0"

[[platform.java17.dependency]]
groupId = "com.oracle.database.xml"
artifactId = "xmlparserv2"
version = "23.2.0.0"
