[package]
org = "ballerinax"
name = "oracledb"
version = "1.4.1"
authors = ["Ballerina"]
keywords = ["database", "client", "network", "SQL", "RDBMS", "OracleDB", "Oracle"]
repository = "https://github.com/ballerina-platform/module-ballerinax-oracledb"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.1.0"

[[platform.java11.dependency]]
path = "../native/build/libs/oracledb-native-1.4.1-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/sql-native-1.6.1-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/ojdbc8-12.2.0.1.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/xdb-21.1.0.0.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/xmlparserv2-12.2.0.1.jar"
scope = "testOnly"
