[package]
org = "ballerinax"
name = "oracledb"
version = "@toml.version@"


[[platform.java11.dependency]]
path = "../oracledb-native/build/libs/oracledb-native-@project.version@.jar"
groupId = "org.ballerinalang"
artifactId = "oracledb-native"
version = "@project.version@"


[[platform.java11.dependency]]
path = "./lib/ojdbc8-12.2.0.1.jar"
artifactId = "ojdbc8"
groupId = "com.oracle.database.jdbc"
scope = "testOnly"
version = "12.2.0.1"