[package]
org = "online"
name = "shop"
version = "0.1.0"

[[dependency]]
org = "ballerinax"
name = "oracledb"
version = "1.0.0"
repository = "local"

[[dependency]]
org = "ballerina"
name = "sql"
version = "1.0.0"
repository = "local"

[[platform.java11.dependency]]
path = "./../../ballerina/lib/ojdbc8-12.2.0.1.jar"

[[platform.java11.dependency]]
path = "./../../ballerina/lib/xdb-21.1.0.0.jar"

[[platform.java11.dependency]]
path = "./../../ballerina/lib/xmlparserv2-12.2.0.1.jar"